/**:
  ros__parameters:
    # ID of anchors in environments 
    anchor_id_lists : [1,2,3,4,5,6,7,8]
    gt_anchor_id_lists : [1,2,3,4,5,6,7,8]
    # Reference coordinate system : Local NED Frame = Front(x) Right(y) Down(z)
    # Anchor Position must be matched with Global Reference Frame definition 
    anchor_pos_x : [ -0.810, -0.810, -0.810,  1.815,  4.440,  4.440,  4.440,  1.815]
    anchor_pos_y : [  0.810, -1.620, -4.050, -4.050, -4.050, -1.620,  0.810, -1.620]
    anchor_pos_z : [  0.000,  0.000,  0.000,  -0.000,  0.000,-0.000,  0.000,  0.000]
    # anchor_pos_x : [2.0, 2.0, 9.0, 12.36, 12.9, 10.6, 12.9, 10.6]
    # anchor_pos_y : [-1.2, 1.2, 1.2, 0.0, 4.3, 4.3, 13.1, 13.1]
    # anchor_pos_z : [0.0, 0.0, 0.0, -1.66, 0.0, 0.0, 0.0, 0.0]
    ### Extrinsic Param (Rotation unit is degree :) )
     # imu to body transformation, (Z -> Y -> X Sequence)
    body_t_imu : [0.0, 0.0, 0.0]
    body_R_imu : [180.0, 0.0, 90.0]
    # radar to imu transformation
    imu_t_radar : [0.0, 0.05, -0.1]
    imu_R_radar : [0.0, 0.0, 90.0]
    # uwb tag to imu translation
    imu_t_uwb : [0.0, -0.05, -0.1]
    # snoar to imu transformationn
    imu_t_sonar : [0.0, 0.0, -0.18]
   
sobang_navigation_node:
    # Reference coordinate system : Forward-Left-Up
  ros__parameters:  
    ### IMU Setting 
    imu_topic : "/imu_apps"
    imu_rate: 900
    do_align : false
    align_time : 10.0
    ### Radar Setting
    radar_topic : "/mmwave/radarScan"
    radar_rate : 20    
    # Sonar Setting
    sonar_topic : "/fmu/out/distance_sensor"
    sonar_rate : 10

    # Prior Information (with respect to  Reference Frame)
    init_pos : [0.0, 0.0, 0.0]
    init_att : [0.0, 0.0, 0.0]
    init_gyro_bias : [-0.000564293, -0.0294942, 0.00547228]
    
    # Standard Deviations of initial state covariance param
    init_pos_cov : [0.8, 0.8, 0.8]    
    init_att_cov : [1.0, 1.0, 1.0]
    init_gyro_bias_cov : [0.001, 0.001, 0.001]
    init_scale_cov : [0.0001, 0.0001, 0.0001]
    
    # Standard Deviations of process noise covariance param
    gyro_noise : [0.001, 0.001, 0.001]
    gyro_bias_noise : [0.0001, 0.0001, 0.0001]
    radar_vel_noise : [0.005, 0.005, 0.005]
    radar_scale_noise : [0.0001, 0.0001, 0.0001]

    # Standard Devications of position, attitude for px4 Measurement
    px4_pos_cov : [0.01, 0.01, 0.01]
    px4_att_cov : [0.01, 0.01, 0.01]
    
    # Measurement Covariance
    uwb_cov : [1.0, 1.0, 2.5]
    # uwb_cov : [1.0, 0.05, 2.5]
    uwb_range_cov : 1.0
    sonar_cov : 0.3

    # Other settings
    view_state : false
    view_path : false
    px4_fc_rate : 50.0

uwb_localizer_node:
  ros__parameters:
    # UWB settings
    uwb_topic : "/sensor/uwb/range"
